version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb
  
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: node bot.js
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: node bot.js
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master

